// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gifts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGift = `-- name: CreateGift :one
INSERT INTO gifts (
    creator_id, title, message, pixel_art, reveal_type, reveal_config,
    view_token, recipient_email, scheduled_open_at, scheduled_send_at,
    single_open, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12
)
RETURNING id, creator_id, title, message, pixel_art, reveal_type, reveal_config, view_token, recipient_email, scheduled_open_at, scheduled_send_at, sent_at, single_open, opened_at, expires_at, created_at, updated_at
`

type CreateGiftParams struct {
	CreatorID       uuid.UUID          `json:"creator_id"`
	Title           string             `json:"title"`
	Message         string             `json:"message"`
	PixelArt        []byte             `json:"pixel_art"`
	RevealType      string             `json:"reveal_type"`
	RevealConfig    []byte             `json:"reveal_config"`
	ViewToken       string             `json:"view_token"`
	RecipientEmail  pgtype.Text        `json:"recipient_email"`
	ScheduledOpenAt pgtype.Timestamptz `json:"scheduled_open_at"`
	ScheduledSendAt pgtype.Timestamptz `json:"scheduled_send_at"`
	SingleOpen      bool               `json:"single_open"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGift(ctx context.Context, arg CreateGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, createGift,
		arg.CreatorID,
		arg.Title,
		arg.Message,
		arg.PixelArt,
		arg.RevealType,
		arg.RevealConfig,
		arg.ViewToken,
		arg.RecipientEmail,
		arg.ScheduledOpenAt,
		arg.ScheduledSendAt,
		arg.SingleOpen,
		arg.ExpiresAt,
	)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Message,
		&i.PixelArt,
		&i.RevealType,
		&i.RevealConfig,
		&i.ViewToken,
		&i.RecipientEmail,
		&i.ScheduledOpenAt,
		&i.ScheduledSendAt,
		&i.SentAt,
		&i.SingleOpen,
		&i.OpenedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGift = `-- name: DeleteGift :execrows
DELETE FROM gifts
WHERE id = $1
`

// Hard delete; media and reactions rows cascade via their FKs. Returns the
// number of rows deleted so the caller can tell "not found" from "deleted".
func (q *Queries) DeleteGift(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGift, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGiftByID = `-- name: GetGiftByID :one
SELECT id, creator_id, title, message, pixel_art, reveal_type, reveal_config, view_token, recipient_email, scheduled_open_at, scheduled_send_at, sent_at, single_open, opened_at, expires_at, created_at, updated_at FROM gifts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGiftByID(ctx context.Context, id uuid.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, getGiftByID, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Message,
		&i.PixelArt,
		&i.RevealType,
		&i.RevealConfig,
		&i.ViewToken,
		&i.RecipientEmail,
		&i.ScheduledOpenAt,
		&i.ScheduledSendAt,
		&i.SentAt,
		&i.SingleOpen,
		&i.OpenedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGiftByViewToken = `-- name: GetGiftByViewToken :one
SELECT id, creator_id, title, message, pixel_art, reveal_type, reveal_config, view_token, recipient_email, scheduled_open_at, scheduled_send_at, sent_at, single_open, opened_at, expires_at, created_at, updated_at FROM gifts
WHERE view_token = $1
LIMIT 1
`

func (q *Queries) GetGiftByViewToken(ctx context.Context, viewToken string) (Gift, error) {
	row := q.db.QueryRow(ctx, getGiftByViewToken, viewToken)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Message,
		&i.PixelArt,
		&i.RevealType,
		&i.RevealConfig,
		&i.ViewToken,
		&i.RecipientEmail,
		&i.ScheduledOpenAt,
		&i.ScheduledSendAt,
		&i.SentAt,
		&i.SingleOpen,
		&i.OpenedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const giftViewTokenExists = `-- name: GiftViewTokenExists :one
SELECT EXISTS (
    SELECT 1 FROM gifts WHERE view_token = $1
)
`

func (q *Queries) GiftViewTokenExists(ctx context.Context, viewToken string) (bool, error) {
	row := q.db.QueryRow(ctx, giftViewTokenExists, viewToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGiftsByUser = `-- name: ListGiftsByUser :many
SELECT id, creator_id, title, message, pixel_art, reveal_type, reveal_config, view_token, recipient_email, scheduled_open_at, scheduled_send_at, sent_at, single_open, opened_at, expires_at, created_at, updated_at FROM gifts
WHERE creator_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGiftsByUser(ctx context.Context, creatorID uuid.UUID) ([]Gift, error) {
	rows, err := q.db.Query(ctx, listGiftsByUser, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gift{}
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Message,
			&i.PixelArt,
			&i.RevealType,
			&i.RevealConfig,
			&i.ViewToken,
			&i.RecipientEmail,
			&i.ScheduledOpenAt,
			&i.ScheduledSendAt,
			&i.SentAt,
			&i.SingleOpen,
			&i.OpenedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGift = `-- name: UpdateGift :one
UPDATE gifts SET
    title             = $1,
    message           = $2,
    pixel_art         = $3,
    reveal_type       = $4,
    reveal_config     = $5,
    recipient_email   = $6,
    scheduled_open_at = $7,
    scheduled_send_at = $8,
    single_open       = $9,
    expires_at        = $10,
    updated_at        = now()
WHERE id = $11
RETURNING id, creator_id, title, message, pixel_art, reveal_type, reveal_config, view_token, recipient_email, scheduled_open_at, scheduled_send_at, sent_at, single_open, opened_at, expires_at, created_at, updated_at
`

type UpdateGiftParams struct {
	Title           string             `json:"title"`
	Message         string             `json:"message"`
	PixelArt        []byte             `json:"pixel_art"`
	RevealType      string             `json:"reveal_type"`
	RevealConfig    []byte             `json:"reveal_config"`
	RecipientEmail  pgtype.Text        `json:"recipient_email"`
	ScheduledOpenAt pgtype.Timestamptz `json:"scheduled_open_at"`
	ScheduledSendAt pgtype.Timestamptz `json:"scheduled_send_at"`
	SingleOpen      bool               `json:"single_open"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ID              uuid.UUID          `json:"id"`
}

// Full-replace of the creator-editable fields (the editor holds the whole gift
// state): passing NULL clears a nullable field. view_token, creator_id and
// created_at are immutable; updated_at is bumped. Ownership is enforced in the
// service, not here.
func (q *Queries) UpdateGift(ctx context.Context, arg UpdateGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, updateGift,
		arg.Title,
		arg.Message,
		arg.PixelArt,
		arg.RevealType,
		arg.RevealConfig,
		arg.RecipientEmail,
		arg.ScheduledOpenAt,
		arg.ScheduledSendAt,
		arg.SingleOpen,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Message,
		&i.PixelArt,
		&i.RevealType,
		&i.RevealConfig,
		&i.ViewToken,
		&i.RecipientEmail,
		&i.ScheduledOpenAt,
		&i.ScheduledSendAt,
		&i.SentAt,
		&i.SingleOpen,
		&i.OpenedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
