// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: magic_links.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

type CreateMagicLinkParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMagicLinkByTokenHash = `-- name: GetMagicLinkByTokenHash :one
SELECT id, user_id, token_hash, expires_at, consumed_at, created_at FROM magic_links
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetMagicLinkByTokenHash(ctx context.Context, tokenHash string) (MagicLink, error) {
	row := q.db.QueryRow(ctx, getMagicLinkByTokenHash, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkConsumed = `-- name: MarkMagicLinkConsumed :one
UPDATE magic_links
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

func (q *Queries) MarkMagicLinkConsumed(ctx context.Context, id uuid.UUID) (MagicLink, error) {
	row := q.db.QueryRow(ctx, markMagicLinkConsumed, id)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
