// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, email string) (User, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
