// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGift(ctx context.Context, arg CreateGiftParams) (Gift, error)
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error)
	CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error)
	CreateUser(ctx context.Context, email string) (User, error)
	// Hard delete; media and reactions rows cascade via their FKs. Returns the
	// number of rows deleted so the caller can tell "not found" from "deleted".
	DeleteGift(ctx context.Context, id uuid.UUID) (int64, error)
	GetGiftByID(ctx context.Context, id uuid.UUID) (Gift, error)
	GetGiftByViewToken(ctx context.Context, viewToken string) (Gift, error)
	GetMagicLinkByTokenHash(ctx context.Context, tokenHash string) (MagicLink, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GiftViewTokenExists(ctx context.Context, viewToken string) (bool, error)
	ListGiftsByUser(ctx context.Context, creatorID uuid.UUID) ([]Gift, error)
	// Chronological wall of reactions for the creator's view (oldest first).
	// Borrar las reacciones al borrar el regalo lo cubre la FK ON DELETE CASCADE;
	// el borrado de una reacción individual (moderación) queda pendiente de diseño.
	ListReactionsByGift(ctx context.Context, giftID uuid.UUID) ([]Reaction, error)
	// Atomic single-open guard (mirrors MarkMagicLinkConsumed): sets opened_at only
	// while it is still NULL, so the first reveal wins and concurrent or repeat calls
	// match no row. A no-rows result means either the gift is already opened or the
	// token is unknown; the caller checks existence separately to tell them apart.
	MarkGiftOpened(ctx context.Context, viewToken string) (Gift, error)
	MarkMagicLinkConsumed(ctx context.Context, id uuid.UUID) (MagicLink, error)
	// Full-replace of the creator-editable fields (the editor holds the whole gift
	// state): passing NULL clears a nullable field. view_token, creator_id and
	// created_at are immutable; updated_at is bumped. published_at is server-managed
	// (set on publish) but written here too so the service can flip it while
	// preserving the rest of the row; the service is what decides its value.
	// Ownership is enforced in the service, not here.
	UpdateGift(ctx context.Context, arg UpdateGiftParams) (Gift, error)
}

var _ Querier = (*Queries)(nil)
