// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReaction = `-- name: CreateReaction :one
INSERT INTO reactions (
    gift_id, kind, emoji, message, voice_storage_key
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, gift_id, kind, emoji, message, voice_storage_key, created_at
`

type CreateReactionParams struct {
	GiftID          uuid.UUID   `json:"gift_id"`
	Kind            string      `json:"kind"`
	Emoji           pgtype.Text `json:"emoji"`
	Message         pgtype.Text `json:"message"`
	VoiceStorageKey pgtype.Text `json:"voice_storage_key"`
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, createReaction,
		arg.GiftID,
		arg.Kind,
		arg.Emoji,
		arg.Message,
		arg.VoiceStorageKey,
	)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.GiftID,
		&i.Kind,
		&i.Emoji,
		&i.Message,
		&i.VoiceStorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listReactionsByGift = `-- name: ListReactionsByGift :many
SELECT id, gift_id, kind, emoji, message, voice_storage_key, created_at FROM reactions
WHERE gift_id = $1
ORDER BY created_at ASC
`

// Chronological wall of reactions for the creator's view (oldest first).
// Borrar las reacciones al borrar el regalo lo cubre la FK ON DELETE CASCADE;
// el borrado de una reacción individual (moderación) queda pendiente de diseño.
func (q *Queries) ListReactionsByGift(ctx context.Context, giftID uuid.UUID) ([]Reaction, error) {
	rows, err := q.db.Query(ctx, listReactionsByGift, giftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reaction{}
	for rows.Next() {
		var i Reaction
		if err := rows.Scan(
			&i.ID,
			&i.GiftID,
			&i.Kind,
			&i.Emoji,
			&i.Message,
			&i.VoiceStorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
